server:
  port: 8001
spring:
  application:
    name: consul-service
  cloud:
    consul:
      port: 8500
      host: 192.168.0.3
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
#        instance-id: ${spring.application.name}-id
