server:
  port: 8080
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.0.3
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: false #²»×¢²áµ½consul

